apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  namespace: devops-tools
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-test-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: web
      path: /metrics
      interval: 15s

