apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32002
      protocol: TCP
