apiVersion: v1
kind: Service
metadata:
  name: python-app-test-svc
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32001
      protocol: TCP
  selector:
    app: python-test-app
