apiVersion: v1
kind: Service
metadata:
  name: python-app-test-svc-internal
  labels:
    app: python-test-app
spec:
  ports:
    - name: web
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: python-test-app
